name: Hexo Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - raw
  schedule:
      - cron:  '0 6 1/2 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      - uses: gameltb/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          use_new_post_cmd: true
          branch: raw
