name: Hexo Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - raw
  schedule:
      - cron:  '0 6 1/6 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: gameltb/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          use_new_post_cmd: true
          branch: raw
